name: Garmin Sync Workflow

on:
  #schedule:
  #  - cron: '27 */1 * * *' # Executes every 1 hour
  workflow_dispatch: # Allows manual triggers from GitHub web UI

jobs:
  sync:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install garminconnect requests
          pip show garminconnect

      - name: Run Garmin Sync
        env:
          GARMIN_TOKENS_BASE64: ${{ secrets.GARMIN_TOKENS_BASE64 }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: python sync_garmin.py
